import { PropsWithChildren, useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
const nav=[['Home','/'],['Who We Are','/about'],['Our Solutions','/services'],['Insights','/insights'],['Sustainability','/sustainability'],['Articles','/articles']];
export function Header(){
  const [open,setOpen]=useState(false);
  const close=()=>setOpen(false);
  return <header>
    <div className="wrap nav">
      <Link to="/" className="logo" onClick={close}><span>P</span><b>Propcare</b><small>ENERGY CARE</small></Link>
      <button type="button" className={`mobile-menu-toggle${open?' is-open':''}`} aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="site-navigation" onClick={()=>setOpen(v=>!v)}><span/><span/><span/></button>
      <nav id="site-navigation" className={open?'site-nav is-open':'site-nav'}>{nav.map(([x,y])=><NavLink key={y} to={y} end={y==='/' } onClick={close}>{x}</NavLink>)}<NavLink className="nav-button" to="/contact" onClick={close}>Contact Us</NavLink></nav>
    </div>
  </header>
}
export function Footer(){return <footer><div className="footer-visual"><img src="https://images.pexels.com/photos/9720534/pexels-photo-9720534.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Power transmission infrastructure"/><div><span className="kicker">Propcare ENERGY CARE</span><h2>Engineering the path<br/>to a cleaner grid.</h2><Link className="button light" to="/contact">Start a project</Link></div></div><div className="wrap footer-main"><div className="footer-brand"><Link className="logo footer-logo" to="/"><span>P</span><b>Propcare</b><small>ENERGY CARE</small></Link><p>Renewable EPC and power infrastructure connecting generation, evacuation and the grid.</p></div><div><b>Explore</b><Link to="/about">About Propcare</Link><Link to="/services">Solutions</Link><Link to="/projects">Projects</Link><Link to="/contact">Contact</Link></div><div><b>Capabilities</b><Link to="/services">Solar EPC</Link><Link to="/services">Wind & electrical</Link><Link to="/services">Substations</Link><Link to="/services">Transmission</Link></div><div><b>Office</b><p>Karur, Tamil Nadu, India</p><Link to="/contact">Project enquiry</Link></div></div><div className="wrap copyright">© {new Date().getFullYear()} Propcare Energy Care Private Limited <span>Renewable EPC · Power Infrastructure</span></div></footer>}
export function HeroVideo(){return <section className="hero-video"><video className="hero-video-frame" autoPlay muted loop playsInline preload="auto" aria-hidden="true" tabIndex={-1}><source src="https://videos.pexels.com/video-files/30915324/13218356_3840_2160_60fps.mp4" type="video/mp4" /></video><div className="hero-shade"/><div className="wrap hero-copy"><span className="kicker">Propcare ENERGY CARE · RENEWABLE EPC & POWER INFRASTRUCTURE</span><h1>Building the infrastructure that moves <i>clean power to the grid.</i></h1><p>Solar. Wind. Evacuation. Substations. Transmission. Testing. Commissioning.</p><div><Link className="button light" to="/services">Explore solutions</Link><Link className="button outline-light" to="/contact">Start a project</Link></div></div></section>}
export function Section({eyebrow,title,children}:{eyebrow:string;title:string;children?:PropsWithChildren['children']}){return <div className="section-head"><span className="kicker">{eyebrow}</span><h2>{title}</h2>{children}</div>}
export function MediaCard({image,title,text}:{image:string;title:string;text:string}){return <article className="media-card"><img src={image} alt=""/><div><span>Propcare</span><h3>{title}</h3><p>{text}</p></div></article>}
