import { PropsWithChildren } from 'react';
import { Link, NavLink } from 'react-router-dom';
export function Arrow(){return <span className="arrow">↗</span>}
const nav=[['About','/about'],['Solutions','/services'],['Projects','/projects'],['Contact','/contact']];
export function Header(){return <header><div className="wrap nav"><Link to="/" className="logo"><span>O</span><b>ORIKS</b><small>ENERGY CARE</small></Link><nav>{nav.map(([x,y])=><NavLink key={y} to={y}>{x}</NavLink>)}<Link className="nav-button" to="/contact">Project enquiry</Link></nav></div></header>}
export function Footer(){return <footer><div className="wrap footer-grid"><div><Link className="logo footer-logo" to="/"><span>O</span><b>ORIKS</b><small>ENERGY CARE</small></Link><p>Renewable EPC and power infrastructure for the generation-to-grid connection.</p></div><div><b>Solutions</b><Link to="/services">Renewable EPC</Link><Link to="/services">Power evacuation</Link><Link to="/services">Substations</Link><Link to="/services">Transmission</Link></div><div><b>Office</b><p>Karur, Tamil Nadu, India</p><Link to="/contact">Start a project <Arrow/></Link></div></div><div className="wrap copyright">© {new Date().getFullYear()} ORIKS Energy Care Private Limited</div></footer>}
export function HeroVideo(){return <section className="hero-video"><video autoPlay muted loop playsInline controls preload="metadata" poster="https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=2200&q=90"><source src="https://videos.pexels.com/video-files/9789925/9789925-hd_1920_1080_25fps.mp4" type="video/mp4"/></video><div className="hero-shade"/><div className="wrap hero-copy"><span className="kicker">ORIKS ENERGY CARE · EPC & POWER INFRASTRUCTURE</span><h1>Engineering the connection between <i>renewable power and the grid.</i></h1><p>Solar. Wind. Evacuation. Substations. Transmission. Commissioning.</p><div><Link className="button light" to="/services">Explore solutions <Arrow/></Link><Link className="button outline-light" to="/contact">Start a project <Arrow/></Link></div></div><div className="hero-label">RENEWABLE POWER / ELECTRICAL INFRASTRUCTURE / TAMIL NADU</div></section>}
export function Section({eyebrow,title,children}:{eyebrow:string;title:string;children?:PropsWithChildren['children']}){return <div className="section-head"><span className="kicker">{eyebrow}</span><h2>{title}</h2>{children}</div>}
export function MediaCard({image,title,text}:{image:string;title:string;text:string}){return <article className="media-card"><img src={image} alt=""/><div><span>ORIKS</span><h3>{title}</h3><p>{text}</p></div></article>}
