import { PropsWithChildren } from 'react';
import { Link, NavLink } from 'react-router-dom';
export function Arrow(){return <span className="arrow">↗</span>}
const nav=[['Home','/'],['Who We Are','/about'],['Our Solutions','/services'],['Insights','/insights'],['Sustainability','/sustainability'],['Articles','/articles']];
export function Header(){return <header><div className="wrap nav"><Link to="/" className="logo"><span>P</span><b>Propcare</b><small>ENERGY CARE</small></Link><nav>{nav.map(([x,y])=><NavLink key={y} to={y} end={y==='/' }>{x}</NavLink>)}<NavLink className="nav-button" to="/contact">Contact Us</NavLink></nav></div></header>}
export function Footer(){return <footer><div className="footer-visual"><img src="https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=2200&q=95" alt="Power transmission infrastructure"/><div><span className="kicker">Propcare ENERGY CARE</span><h2>Engineering the path<br/>to a cleaner grid.</h2><Link className="button light" to="/contact">Start a project <Arrow/></Link></div></div><div className="wrap footer-main"><div className="footer-brand"><Link className="logo footer-logo" to="/"><span>P</span><b>Propcare</b><small>ENERGY CARE</small></Link><p>Renewable EPC and power infrastructure connecting generation, evacuation and the grid.</p></div><div><b>Explore</b><Link to="/about">About Propcare</Link><Link to="/services">Solutions</Link><Link to="/projects">Projects</Link><Link to="/contact">Contact</Link></div><div><b>Capabilities</b><Link to="/services">Solar EPC</Link><Link to="/services">Wind & electrical</Link><Link to="/services">Substations</Link><Link to="/services">Transmission</Link></div><div><b>Office</b><p>Karur, Tamil Nadu, India</p><Link to="/contact">Project enquiry <Arrow/></Link></div></div><div className="wrap copyright">© {new Date().getFullYear()} Propcare Energy Care Private Limited <span>Renewable EPC · Power Infrastructure</span></div></footer>}
export function HeroVideo(){return <section className="hero-video"><iframe className="hero-video-frame" src="https://www.youtube.com/embed/S3kbnaeohSQ?autoplay=1&mute=1&loop=1&playlist=S3kbnaeohSQ&controls=0&rel=0&modestbranding=1&playsinline=1" title="Renewable energy infrastructure video" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/><div className="hero-shade"/><div className="wrap hero-copy"><span className="kicker">Propcare ENERGY CARE · RENEWABLE EPC & POWER INFRASTRUCTURE</span><h1>Building the infrastructure that moves <i>clean power to the grid.</i></h1><p>Solar. Wind. Evacuation. Substations. Transmission. Testing. Commissioning.</p><div><Link className="button light" to="/services">Explore solutions <Arrow/></Link><Link className="button outline-light" to="/contact">Start a project <Arrow/></Link></div></div></section>}
export function Section({eyebrow,title,children}:{eyebrow:string;title:string;children?:PropsWithChildren['children']}){return <div className="section-head"><span className="kicker">{eyebrow}</span><h2>{title}</h2>{children}</div>}
export function MediaCard({image,title,text}:{image:string;title:string;text:string}){return <article className="media-card"><img src={image} alt=""/><div><span>Propcare</span><h3>{title}</h3><p>{text}</p></div></article>}
