const solar='https://images.pexels.com/photos/15751120/pexels-photo-15751120.jpeg?auto=compress&cs=tinysrgb&w=2200';
const grid='https://images.pexels.com/photos/18468536/pexels-photo-18468536.jpeg?auto=compress&cs=tinysrgb&w=2200';
const transmission='https://images.pexels.com/photos/14939042/pexels-photo-14939042.jpeg?auto=compress&cs=tinysrgb&w=2200';

export const works=[
 {slug:'solar',category:'SOLAR / GENERATION',title:'Solar Projects',short:'Solar EPC support, electrical balance-of-plant and grid-facing infrastructure for utility, commercial and industrial assets.',headline:'Build the plant with the grid in mind.',description:'Solar delivery is not only a module-and-structure exercise. It depends on site conditions, DC and AC systems, protection, evacuation, testing, documentation and the operating context around the plant.',image:'https://images.pexels.com/photos/15663101/pexels-photo-15663101/free-photo-of-solar-panel-field.jpeg?auto=compress&cs=tinysrgb&w=2200',bullets:['Site and EPC scope coordination','DC / AC electrical infrastructure','Power evacuation interfaces','HT, protection and metering coordination','Testing, documentation and handover'],details:['Translate drawings and site constraints into an executable package.','Coordinate electrical systems around the generation block and balance-of-plant.','Keep plant output connected to the receiving infrastructure and schedule.','Align equipment, protection, cable and grid-interface requirements.','Build evidence into construction and commissioning instead of after it.'],steps:['Review site, drawings and delivery scope','Coordinate procurement and construction interfaces','Inspect, test and resolve punch points','Compile handover evidence'],stepDetails:['Confirm access, layout, quantities, interfaces and milestones.','Keep contractors and material readiness aligned to the work sequence.','Verify installation quality and functional readiness.','Close documentation gaps before the package is considered complete.']},
 {slug:'windmill',category:'WIND / TURBINE INFRASTRUCTURE',title:'Wind Projects',short:'Electrical infrastructure, balance-of-plant coordination and site interfaces for wind-energy projects.',headline:'Wind projects combine power infrastructure with difficult physical access.',description:'Wind sites add long-distance access, turbine-component logistics, construction sequencing and electrical collection or evacuation interfaces. Propercare separates those constraints, then reconnects them into one delivery sequence.',image:'https://images.pexels.com/photos/2888337/pexels-photo-2888337.jpeg?auto=compress&cs=tinysrgb&w=2200',bullets:['Wind-farm electrical works','Collection and pooling systems','Evacuation infrastructure','Turbine-site interface coordination','Testing and commissioning'],details:['Coordinate site electrical packages around turbine and civil interfaces.','Support collection and pooling infrastructure from turbine strings toward the grid interface.','Plan the receiving infrastructure with protection and energisation in view.','Make access, delivery windows and site readiness visible to the project team.','Close the loop through inspection, testing and commissioning records.'],steps:['Map turbine, electrical and logistics interfaces','Prepare package sequence and site readiness','Execute electrical and support works','Test, energise and hand over'],stepDetails:['Identify dependencies between turbine deliveries, civil works and electrical packages.','Align materials, crews, access and work fronts.','Control construction against the approved sequence.','Compile test results and readiness evidence for the next stage.']},
 {slug:'transport',category:'ODC / HEAVY MOVEMENT',title:'Transport & Logistics',short:'Route-led movement of oversized renewable and industrial equipment, from cargo assessment through site delivery.',headline:'The safest heavy movement is engineered before it moves.',description:'Industry leaders in wind and ODC logistics emphasise cargo analysis, route surveys, equipment selection, permits, escorts, staging and site readiness. Propercare uses that project logic to frame every movement enquiry.',image:'https://images.pexels.com/photos/2199293/pexels-photo-2199293.jpeg?auto=compress&cs=tinysrgb&w=2200',bullets:['Cargo and dimension assessment','Route survey and feasibility','ODC equipment planning','Permit and movement coordination','Site delivery and handover'],details:['Start with the actual dimensions, weight, lifting points and handling limitations.','Review roads, turns, bridges, clearances, access and temporary works.','Match the transport configuration to cargo and route conditions.','Coordinate the approvals and movement controls needed for execution.','Align arrival, unloading, lifting and site acceptance.'],steps:['Capture cargo and origin / destination data','Survey and validate the route','Engineer the movement and mobilisation','Deliver, unload and close the movement'],stepDetails:['Gather drawings, dimensions, weight, target dates and site contacts.','Identify constraints before equipment is committed.','Define configuration, sequence, controls and responsibilities.','Coordinate the final approach and proof of delivery.']}
];
export const services=[
 {slug:'epc',code:'EPC',title:'EPC & EBoP',lead:'Integrated project support from engineering scope through construction and handover.',headline:'Make engineering intent executable at site.',description:'A coordinated package for renewable infrastructure where engineering, procurement, construction, quality and handover have to move as one sequence.',short:'Engineering, procurement and construction packages coordinated around site realities and handover requirements.',image:works[0].image,why:'Renewable EPC work creates risk at the interfaces between design, materials, contractors and site execution.',outcome:'Propercare focuses on making responsibilities, readiness and acceptance criteria visible before field activity accelerates.',checkpoints:[['SCOPE','Drawings, quantities, responsibilities and acceptance criteria are clear.'],['MATERIAL','Critical equipment and materials are aligned with the construction sequence.'],['SITE','Work fronts, access, safety controls and contractor interfaces are ready.'],['CLOSE','Quality records, testing and punch-list closure support handover.']]},
 {slug:'evacuation',code:'EVACUATION',title:'Power Evacuation',lead:'Plant-to-grid infrastructure coordinated around collection, transformation, protection and energisation.',headline:'The generation plant is only useful when the power can leave it.',description:'Power evacuation packages connect the generating asset to the receiving network through cables, transformers, switchgear, protection, metering and associated interfaces.',short:'Collection, transformation and grid-interface infrastructure from plant to receiving point.',image:transmission,why:'Evacuation systems cross electrical, civil, protection and grid-approval boundaries.',outcome:'We organise the package around those dependencies so construction and commissioning are sequenced toward energisation.',checkpoints:[['COLLECTION','Cable routes, terminations and collection interfaces are defined.'],['TRANSFORM','Transformer and switchgear interfaces are coordinated.'],['PROTECTION','Protection, metering and control requirements are tracked.'],['ENERGISE','Tests, records and readiness checks support energisation.']]},
 {slug:'substations',code:'SUBSTATIONS',title:'Substations & Switchyards',lead:'Primary and secondary systems coordinated for controlled power transfer, protection and metering.',headline:'A substation is a system of interfaces, not a single equipment list.',description:'Delivery requires coordination across layout, primary equipment, control, protection, earthing, cabling, interlocking, testing and as-built documentation.',short:'Primary and secondary systems for controlled power transfer, protection and metering.',image:grid,why:'Substation packages become difficult when primary, secondary and commissioning workstreams drift apart.',outcome:'Our delivery view keeps equipment, wiring, testing and documentation moving toward the same energisation milestone.',checkpoints:[['PRIMARY','Equipment layout, clearances and interfaces are aligned.'],['SECONDARY','Control, protection, metering and interlocking are coordinated.'],['TEST','Inspection and functional test sequences are agreed.'],['HANDOVER','As-built records and test evidence are complete.']]},
 {slug:'testing',code:'TESTING',title:'Testing & Commissioning',lead:'Inspection, testing, functional verification and handover support before an asset enters operation.',headline:'Commissioning is where the project proves itself.',description:'Testing turns installed equipment into an operating system. It needs approved methods, traceable records, issue control and clear readiness decisions.',short:'Inspection, testing, functional verification and synchronisation support before handover.',image:'https://images.pexels.com/photos/33689077/pexels-photo-33689077/free-photo-of-engineer-inspects-power-transmission-tower-outdoors.jpeg?auto=compress&cs=tinysrgb&w=2200',why:'A technically complete installation can still be operationally unready if testing evidence and interfaces are incomplete.',outcome:'We help structure inspection, testing, defect close-out and readiness documentation around the energisation sequence.',checkpoints:[['PLAN','Test methods, instruments, responsibilities and prerequisites are known.'],['VERIFY','Equipment, cables, protection and interlocks are checked.'],['CLOSE','Defects and punch points are tracked to resolution.'],['PROVE','Test records and readiness evidence support handover.']]}
];
export const sectors=[
 {name:'SOLAR',focus:'Generation + electrical balance-of-plant'},
 {name:'WIND',focus:'Turbine sites + collection + access'},
 {name:'ODC',focus:'Cargo + route + site delivery'}
];
export const clients=[
 {name:'Renewable developers & asset owners',need:'Need predictable progress, visible risk and confidence that site packages are ready when required.',value:'Visibility + accountability'},
 {name:'EPC contractors',need:'Need execution support that fits an existing engineering package without creating new coordination gaps.',value:'Interface discipline'},
 {name:'Wind & solar OEM ecosystems',need:'Need site, electrical and logistics activities to respect equipment and delivery requirements.',value:'Technical coordination'},
 {name:'Industrial project teams',need:'Need heavy equipment and infrastructure moved safely through constrained routes and sites.',value:'Route-led planning'},
 {name:'Power & grid stakeholders',need:'Need protection, testing, documentation and energisation readiness to converge.',value:'Commissioning readiness'},
 {name:'Operations & maintenance teams',need:'Need clear records and practical handover information after construction activity ends.',value:'Lifecycle continuity'}
];
export const articles=[
 {slug:'india-renewable-buildout-2026',tag:'MARKET',date:'05 OCT 2026',readTime:'6 MIN READ',title:'India’s renewable buildout is accelerating — but execution is becoming the real differentiator',text:'India’s renewable capacity continues to expand at record pace. For EPC and infrastructure teams, the harder question is no longer whether projects will be built, but whether land, transmission, procurement and commissioning can keep up.',image:solar,source:'https://mnre.gov.in/en/physical-progress/',sourceName:'MNRE — Physical Achievements',content:[['The scale is moving quickly','MNRE reported 168.04 GW of cumulative solar capacity and 58.52 GW of wind capacity as of 31 August 2026. Solar additions during April–August 2026 alone were 17.78 GW, while wind additions reached 2.43 GW.'],['Execution is now a systems problem','The strongest project teams treat engineering, procurement, construction, evacuation and commissioning as connected workstreams. A delay in one interface can hold back an otherwise complete plant.'],['What this means for EPC teams','Project plans should identify material readiness, access, grid interfaces, protection requirements, testing prerequisites and documentation milestones before mobilisation. The objective is predictable progress, not activity for activity’s sake.']]},
 {slug:'solar-market-1h-2026',tag:'SOLAR',date:'05 OCT 2026',readTime:'5 MIN READ',title:'27 GW in six months: what India’s 1H 2026 solar record means for project execution',text:'India added a record 27 GW of solar in the first half of 2026. The next competitive advantage is turning awarded capacity into commissioned, grid-ready assets without losing control of interfaces.',image:solar,source:'https://www.mercomindia.com/india-adds-record-27-gw-of-solar-capacity-in-first-half-of-2026',sourceName:'Mercom India Research',content:[['A record first half','Mercom India reported 27 GW of solar capacity additions in 1H 2026, 49% higher than the same period in 2025. Cumulative solar capacity reached about 165 GW by June 2026.'],['The pipeline is not the same as completed infrastructure','Land, transmission connectivity, equipment availability, PPAs and approvals still determine whether projects move from awarded capacity to energised assets. Large-scale projects represented 83% of cumulative solar capacity at mid-year.'],['The EPC implication','The execution plan should connect DC works, AC collection, transformers, switchgear, evacuation, protection, testing and handover rather than managing them as isolated packages.']]},
 {slug:'tamil-nadu-open-access',tag:'TAMIL NADU',date:'05 OCT 2026',readTime:'5 MIN READ',title:'Tamil Nadu’s solar open-access market: why execution discipline matters',text:'Tamil Nadu remains an important market for renewable power procurement. For C&I customers and project developers, commercial opportunity increasingly depends on predictable implementation and grid readiness.',image:grid,source:'https://www.mercomindia.com/solar-and-battery-storage-lead-ci-shift-toward-clean-power-procurement',sourceName:'Mercom India — C&I Research',content:[['A strong C&I use case','Mercom reported approximately 2.7 GW of solar open-access capacity in Tamil Nadu as of September 2025, underlining the state’s importance in the segment.'],['Open access creates more interfaces','Project success depends on generation, scheduling, evacuation, approvals, metering and the receiving consumer or network. These interfaces need to be planned together.'],['Why local execution matters','Site access, contractor coordination, inspection and documentation can materially affect the commissioning timeline. A field partner should make these dependencies visible early and keep evidence aligned with the final energisation sequence.']]},
 {slug:'solar-plus-storage',tag:'STORAGE',date:'05 OCT 2026',readTime:'5 MIN READ',title:'Why solar projects are becoming storage-and-grid projects',text:'Battery storage is moving closer to the centre of renewable project planning as developers and policymakers focus on grid flexibility and reliability.',image:transmission,source:'https://mnre.gov.in/en/whats-new/',sourceName:'MNRE — What’s New',content:[['The policy signal is clear','MNRE’s current updates include viability-gap-funding measures for battery energy storage and an advisory on co-locating storage with solar projects to improve grid stability and cost efficiency.'],['Storage changes the execution sequence','A solar-plus-storage project introduces additional equipment, protection, controls, cabling, testing and operational interfaces. These should be reflected in engineering and commissioning plans from the beginning.'],['The practical takeaway','EPC teams should define where storage connects, how protection and controls interact, what testing proves readiness and which documents are required before commercial operation.']]},
 {slug:'wind-logistics-route-intelligence',tag:'WIND',date:'05 OCT 2026',readTime:'6 MIN READ',title:'Wind logistics starts with route intelligence, not a truck',text:'As turbine components become larger and routes more constrained, safe wind logistics depends on understanding the complete journey before selecting the movement configuration.',image:wind,source:'https://www.bws.net/solutions/transport/wind-turbine-transport',sourceName:'Blue Water Shipping — Wind Turbine Transport',content:[['Start with the cargo','Blade length, nacelle dimensions, tower sections, weight, lifting points and handling limits define the movement problem. Cargo data should be complete before transport equipment is committed.'],['Then engineer the route','Road geometry, bridges, clearances, turning radii, gradients, utilities, temporary works and site approach can change the feasibility of a movement. Route surveys convert assumptions into decisions.'],['Finally connect route to site readiness','Arrival is only successful when the receiving site can accept, unload, stage and move the component to its final position. Transport planning should therefore sit alongside civil and construction sequencing.']]},
 {slug:'odc-cargo-first',tag:'LOGISTICS',date:'05 OCT 2026',readTime:'5 MIN READ',title:'ODC planning: cargo first, equipment second',text:'Oversized and heavy cargo movements become more predictable when the cargo characteristics drive the transport configuration rather than the other way around.',image:transport,source:'https://www.ntclogistics.in/renewable-logistics/',sourceName:'NTC Logistics — Renewable Logistics',content:[['The cargo defines the problem','Dimensions, gross weight, centre of gravity, lifting points, fragility and unloading requirements determine what equipment and route controls are appropriate.'],['Customisation can be necessary','Renewable logistics providers increasingly describe specialised trailers and project-specific configurations because standard fleet assumptions do not always fit long blades, heavy equipment or constrained access.'],['Treat the final kilometres as engineering','A route can be technically passable yet operationally difficult at the site gate. Arrival geometry, laydown space, lifting access and timing need the same attention as the public-road journey.']]},
 {slug:'commissioning-as-proof',tag:'COMMISSIONING',date:'05 OCT 2026',readTime:'5 MIN READ',title:'Commissioning is not paperwork — it is the project proving itself',text:'A technically installed asset is not automatically an operationally ready asset. Testing and commissioning turn installation into evidence that the system can operate as intended.',image:grid,source:'https://www.mercomindia.com/predictable-execution-by-solar-epcs-key-to-long-term-value-creation-interview',sourceName:'Mercom India — EPC Execution',content:[['Installation and readiness are different states','Equipment can be physically installed while protection settings, cable tests, interlocks, documentation or interface approvals remain incomplete.'],['Build the test sequence early','Testing should be linked to construction completion, prerequisites, instruments, responsibilities and issue closure. This prevents the commissioning team from discovering basic readiness gaps at the end.'],['Handover should contain evidence','A strong close-out package includes test results, as-built information, punch-list status and clear acceptance records. The document trail should reflect what was actually proven in the field.']]},
 {slug:'what-good-renewable-website-content-does',tag:'INSIGHT',date:'05 OCT 2026',readTime:'4 MIN READ',title:'What the best renewable infrastructure websites communicate differently',text:'Our research across logistics, EPC, OEM and renewable-energy companies revealed a consistent pattern: the strongest sites explain how work gets done, not just what services exist.',image:grid,source:'https://nabrostransport.com/',sourceName:'Industry reference set',content:[['Capability is organised around customer decisions','Specialists such as Nabros and NTC separate wind, heavy transport and renewable logistics into understandable packages. That makes complex services easier to discover.'],['Project stories create proof','Case-study structures from logistics and energy companies show the value of explaining the challenge, engineering approach, execution and outcome rather than publishing generic claims.'],['Education builds trust before the enquiry','Useful articles can answer questions about route surveys, EPC scope, commissioning, grid interfaces and project readiness before a customer ever fills out a form. That is the direction of Propercare’s new content strategy.']]}
];
export const research=[
 {name:'Nabros Transport',category:'ODC / WIND LOGISTICS',learning:'A strong benchmark for capability-led navigation: wind transport, heavy & specialised transport, route survey, multimodal movement, warehousing, safety and case studies.',url:'https://nabrostransport.com/'},
 {name:'Terravolt Renewables',category:'WIND SERVICES',learning:'Useful service structure around factory-to-site WTG transport, yard management, intercarting and crane packages.',url:'https://terravolt.in/services/'},
 {name:'Sangreen Future Renewables',category:'RENEWABLE LOGISTICS',learning:'Reference for route surveys, heavy-lift planning and turnkey wind-project logistics positioning.',url:'https://sangreenrenewables.com/logistics/'},
 {name:'DB Schenker',category:'PROJECT CASE STUDY',learning:'A useful global reference for presenting a difficult wind-blade movement as a measurable project story rather than a generic service claim.',url:'https://www.dbschenker.com/global/insights/news-and-stories/press-releases/wind-turbine-blades-india-1771614'},
 {name:'Blue Water Shipping',category:'GLOBAL WIND LOGISTICS',learning:'Strong example of explaining changing turbine sizes, OOG handling methods, Ro/Ro movements and project track record.',url:'https://www.bws.net/solutions/transport/wind-turbine-transport'},
 {name:'NTC Logistics',category:'RENEWABLE LOGISTICS',learning:'Benchmark for separating renewable logistics into wind, solar and hydro while connecting specialised fleet, project logistics and tracking.',url:'https://www.ntclogistics.in/renewable-logistics/'},
 {name:'ReGen Powertech',category:'WIND TECHNOLOGY',learning:'Shows the value of explaining clean-energy expertise through products, project execution, engineering capability and news.',url:'https://www.regenpowertech.com/'},
 {name:'SWELECT Energy Systems',category:'SOLAR TECHNOLOGY',learning:'Useful product-led model covering PV modules, mounting structures, electrical BOS, pumps, packaged solar systems and storage.',url:'https://swelectes.com/'},
 {name:'Orient Green Power',category:'WIND POWER',learning:'Reference for communicating renewable generation assets as a business segment rather than only as a service.',url:'https://www.orientgreenpower.com/wind-power.asp'},
 {name:'Heliostrom',category:'CHENNAI SOLAR',learning:'Strong local conversion pattern: residential, commercial and industrial solar, site survey, system design, installation, testing and approvals.',url:'https://www.heliostrom.com/'},
 {name:'Ksquare Energy',category:'SOLAR EPC / LOCAL',learning:'Useful example of location-led solar discovery and broad service coverage across Indian markets.',url:'https://www.ksquareenergy.com/solar-company-in-chennai'},
 {name:'AceRenewTech',category:'SOLAR EPC / CHENNAI',learning:'Clear explanation of the EPC sequence: design, engineering and construction, with separate residential, C&I and utility-scale use cases.',url:'https://acerenewtech.com/blogs/solar-epc-companies-in-chennai/'},
 {name:'Tata Power Renewables',category:'NATIONAL RENEWABLES',learning:'Enterprise reference for presenting renewable energy alongside wider energy infrastructure, customer journeys and operational scale.',url:'https://www.tatapower.com/renewables'},
 {name:'Adani Green Energy',category:'UTILITY RENEWABLES',learning:'Useful benchmark for combining generation scale, sustainability, water stewardship, reporting and stakeholder communication.',url:'https://www.adanigreenenergy.com/'},
 {name:'L&T Green Energy',category:'ENGINEERING & INFRASTRUCTURE',learning:'Reference for positioning renewables within a larger engineering capability across solar, wind and infrastructure delivery.',url:'https://www.larsentoubro.com/green-energy'}
];
